/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sales.and.inventory.management.system;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author juanm
 */
public class Registration extends javax.swing.JFrame {

    private static final String username = JDBC.username;
    private static final String password = JDBC.password;
    private static final String dataConn = JDBC.dataConn;

    Connection sqlConn =null;
    PreparedStatement pst = null;
    PreparedStatement pst2 = null, pst3 = null;
    ResultSet rs=null, rs2=null,rs3=null;
        
    public Registration() {
        initComponents();
        JDBC db = new JDBC();
        db.Connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtPhoneNum = new TextField("Phone number");
        cboUDesignation = new Combobox<>("User type");
        txtFname = new TextField("First name");
        txtLname = new TextField("Last name");
        txtEmail = new TextField("Email");
        txtUname = new TextField("Username");
        txtUpass = new PasswordField("Password");
        Agreement = new javax.swing.JCheckBox();
        Signup = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        txtConfirm = new PasswordField("Confirm Password");
        jLabel13 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(1, 60, 88));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel2.setBackground(new java.awt.Color(255, 0, 255));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign up");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtPhoneNum.setBackground(new java.awt.Color(255, 255, 255));
        txtPhoneNum.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPhoneNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneNumFocusLost(evt);
            }
        });
        txtPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumActionPerformed(evt);
            }
        });
        txtPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumKeyTyped(evt);
            }
        });

        cboUDesignation.setBackground(new java.awt.Color(255, 255, 255));
        cboUDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","Owner", "Cashier" }));

        txtFname.setBackground(new java.awt.Color(255, 255, 255));
        txtFname.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnameFocusLost(evt);
            }
        });
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFnameKeyTyped(evt);
            }
        });

        txtLname.setBackground(new java.awt.Color(255, 255, 255));
        txtLname.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLnameFocusLost(evt);
            }
        });
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLnameKeyTyped(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtUname.setBackground(new java.awt.Color(255, 255, 255));
        txtUname.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnameFocusLost(evt);
            }
        });
        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });

        txtUpass.setBackground(new java.awt.Color(255, 255, 255));
        txtUpass.setActionCommand("<Not Set>");
        txtUpass.setMinimumSize(new java.awt.Dimension(64, 30));
        txtUpass.setPreferredSize(new java.awt.Dimension(64, 30));

        Agreement.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Agreement.setForeground(new java.awt.Color(102, 102, 102));
        Agreement.setText("I agree to all  terms and policies");
        Agreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreementActionPerformed(evt);
            }
        });

        Signup.setBackground(new java.awt.Color(1, 60, 88));
        Signup.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Signup.setForeground(new java.awt.Color(255, 255, 255));
        Signup.setText("Sign Up");
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupMouseClicked(evt);
            }
        });
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 0, 255));
        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Already have an account?");

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 83, 122));
        Login.setText("Login");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });

        txtConfirm.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirm.setActionCommand("<Not Set>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Login))
                    .addComponent(Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpass, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFname))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLname)
                            .addComponent(txtPhoneNum)
                            .addComponent(cboUDesignation, 0, 265, Short.MAX_VALUE)
                            .addComponent(txtConfirm)))
                    .addComponent(Agreement))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboUDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUpass, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(Agreement)
                .addGap(20, 20, 20)
                .addComponent(Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Login))
                .addGap(43, 43, 43))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/register.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained

    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneNumFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumFocusGained

    private void txtPhoneNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneNumFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumFocusLost

    private void txtPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumActionPerformed

    private void txtFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameFocusGained

    private void txtFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameFocusLost

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameFocusGained

    private void txtLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameFocusLost

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtUnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameFocusGained

    private void txtUnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameFocusLost

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void AgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgreementActionPerformed

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        Signin show = new Signin();
        show.setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginMouseClicked

    private void SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseClicked
        
    }//GEN-LAST:event_SignupMouseClicked

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        CREATE:try
        {        
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("SELECT COUNT(*) FROM user");        
            rs = pst.executeQuery();
            String phone = txtPhoneNum.getText();
            String Uname = txtUname.getText();
            String Upass = txtUpass.getText();
            String UFname = txtFname.getText();
            String ULname = txtLname.getText();
            String UEmail = txtEmail.getText();
            String UPhonenumber = txtPhoneNum.getText();
            String Des = (String)cboUDesignation.getSelectedItem();
            int Unamelength = Uname.length();
            int Upasslength = Upass.length();
            int UFnamelength = UFname.length();
            int ULnamelength = ULname.length();
            int UEmaillength = UEmail.length();
            int UPhonenumberlength = UPhonenumber.length();            
            if(rs.next()){         
            int rowcount = rs.getInt(1);   
                if(rowcount==0 || rowcount>=1){
                CreateAccount(Uname,Upass,UFname,ULname,UEmail,UPhonenumber,phone,Unamelength,Upasslength,UFnamelength,ULnamelength,UEmaillength,UPhonenumberlength, Des);  
                break CREATE;
                 }                 
         }                   
        }  
         catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesAndInventoryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact your admin to find the necessary class.");
        } catch (SQLException | NumberFormatException ex ) {
             //System.err.println(ex);
            java.util.logging.Logger.getLogger(SalesAndInventoryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Incomplete Account Information, please try again.");
        }
        //System.err.println(ex);
        catch(Exception ex){
            java.util.logging.Logger.getLogger(SalesAndInventoryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact your admin for assistance.");
        }

        
    }//GEN-LAST:event_SignupActionPerformed

    private void txtPhoneNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumKeyTyped
            char c = evt.getKeyChar();
            if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
                evt.consume();              
            }
            int limit = 10;
            int PhoneNumlength = txtPhoneNum.getText().length();
            if(PhoneNumlength > limit){
                evt.consume();
            }
    }//GEN-LAST:event_txtPhoneNumKeyTyped

    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyTyped
            char c = evt.getKeyChar();
            if((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
                evt.consume();              
            }
    }//GEN-LAST:event_txtFnameKeyTyped

    private void txtLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyTyped
            char c = evt.getKeyChar();
            if((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
                evt.consume();              
            }
    }//GEN-LAST:event_txtLnameKeyTyped
        public void CreateAccount(String Uname, String Upass, String UFname, String ULname, String UEmail, String UPhonenumber, String phone, int Unamelength, int Upasslength,int UFnamelength, int ULnamelength, int UEmaillength, int UPhonenumberlength, String Des){
        CREATE:
        try {
            pst = sqlConn.prepareStatement("INSERT into user(UFname, ULname, Uname, Upass, UDesignation, ULevel, UEmail, UPhonenumber)values"
                    + "(?,?,?,?,?,?,?,?)");            
            pst.setString(1, txtFname.getText());
            pst.setString(2, txtLname.getText());
            pst.setString(3, txtUname.getText());
            pst.setString(4, txtUpass.getText());
            pst.setString(5, (String)cboUDesignation.getSelectedItem()); 
            pst.setString(7, txtEmail.getText());         
            pst.setString(8, phone);
            if("Owner".equals(Des)){
                //Owner User Level
                pst.setInt(6, 2);
            }
            else{
                //Cashier User Level
                pst.setInt(6, 1);
            } 
            pst2 = sqlConn.prepareStatement("SELECT Uname FROM user"); 
            rs2 = pst2.executeQuery();
            ArrayList list = new ArrayList();
            String uname = txtUname.getText();
                while(rs2.next()){                 
                    String user = rs2.getString("Uname");                                          
                    list.add(user);                                         
                }
                //Checking for duplicates
                if(list.contains(uname)){
                    JOptionPane.showMessageDialog(this, "Username already exists! Please try again."); 
                }               
                    
                else if(uname==null){
                    JOptionPane.showMessageDialog(this, "Please input username.");                               
                }
                else{
                        if(Unamelength == 0 || Upasslength == 0 || UFnamelength == 0 || ULnamelength == 0 || UEmaillength == 0 || UPhonenumberlength == 0) {
                            JOptionPane.showMessageDialog(this, "Incomplete Account Information, please try again.");
                            break CREATE;
                        }
                        if(Unamelength < 8 ){
                            JOptionPane.showMessageDialog(this, "Username should have 8 characters or more. Please try again.");
                            break CREATE;
                        }
                        if(Upasslength < 10 ){
                            JOptionPane.showMessageDialog(this, "Password should have 10 characters or more. Please try again.");
                            break CREATE;
                        }
                        if(UPhonenumberlength != 11){
                            JOptionPane.showMessageDialog(this, "Invalid Phone number. Please try again.");
                            break CREATE;
                        }
                        if(UPhonenumberlength != 11||!UPhonenumber.startsWith("09")){
                            JOptionPane.showMessageDialog(this, "Invalid Phone number. Please try again.");
                            break CREATE;
                        }
                        if(!UEmail.contains("@")&&!UEmail.contains(".com")){
                            JOptionPane.showMessageDialog(this, "Invalid Email Address. Please try again.");
                            break CREATE;
                        }
                       Pattern letter = Pattern.compile("[a-zA-z]");
                       Pattern digit = Pattern.compile("[0-9]");
                       Pattern special = Pattern.compile ("[!@#$%&*()_+=|<>?{}\\[\\]~-]");
                        //Pattern eight = Pattern.compile (".{8}");
                       Matcher hasLetter = letter.matcher(Upass);
                       Matcher hasDigit = digit.matcher(Upass);
                       Matcher hasSpecial = special.matcher(Upass);
                       if(hasLetter.find()&&hasDigit.find()&&hasSpecial.find()){
                            String UpassConfirm = txtConfirm.getText();
                            if(Upass.equals(UpassConfirm)){
                                pst.executeUpdate();
                                pst.close();
                                JOptionPane.showMessageDialog(this, "Account successfully created!");
                                dispose();              
                                Signin signin = new Signin();
                                signin.setVisible(true); 
                            }
                            else{
                            JOptionPane.showMessageDialog(this, "Password doesn't match, please try again.");
                            break CREATE;    
                            }               
                       }
                       else{
                           JOptionPane.showMessageDialog(this, "Password should have letters, numbers and atleast 1 special character, please try again.");
                           break CREATE;
                       }
             
                    sqlConn.close(); 
                    
                    }
                           
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Agreement;
    private javax.swing.JLabel Login;
    private javax.swing.JButton Signup;
    private javax.swing.JComboBox<String> cboUDesignation;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtUname;
    private javax.swing.JPasswordField txtUpass;
    // End of variables declaration//GEN-END:variables
}


